language: node_js
node_js:
- node
- '8'
cache:
  yarn: true
env:
- PORT=3000
notifications:
  slack:
    secure: dDMHdhfvS1TV9r5MKDKAWUeC2J1sjn1P89KwiQXLOCjbf9mMp2X43Req/TNSYFG+B1SEgFI4V0f+y77L+/iknNYmnljBJZoNCmuM8uWFnelncVm3QJJwyv/SNj4nFo0xnaRbg6mJ0HFGTO460EyaPAVxnhCRMK2dLiFFiz8xpIGIT22C9U/pgyq4FB5bvZaU85TpWwteydGKOOlPlDxVhv3Kl3B/Tqb7PN6kvipBLMi1bp81fgKN4VXJdL5GGxOhj27wJS2kKzJ9XBgxXw8YSEtDU/6gm0YjfNimxEW83L6ixTpe+TAcE6vXGjvLvhypMyDLovlyxV3aMdrOp5z+MZys+RwEue6eLvKVDFieFFNYrR9nCTtTSVedNd3OliN9MQrO57ZJzFIm7p8fe1BY+5LPROxt3oeHIJob00U99kzHyl81OtGXUc3yU99xL5lNCyAXr0x2dKOt/+D77RgnVHJoY3A9Okfy05UP3pDQZEVVGPdJCivnogKvTmblq2SAt2wVyxpPFJi6sxeLOUoVHseb8IKkt6ZC3qoMzURUL36UZakJKLsN0XrxPEHZbwBNwkBn7LUF7TY07TkDR4rE3G8l1bEGoY9UhfjqrC2cRdhgUTDXQR5W0w1iYaEQnp2TsJA6GBImspY+zX2IczwYy+ey2bnOHQcghAeHoVjAoJw=
